[build]
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(windows)']
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
xtask = "run --package xtask --"
dev = "xtask dev"
